name: Compile PoC Application

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Xcode 15.4
      - name: Set up Xcode 15.4
        run: |
          # Ensure the correct version of Xcode is selected
          sudo xcode-select --switch /Applications/Xcode_15.4.app/Contents/Developer
          xcodebuild -version

      # Step 3: Validate Xcode project compatibility
      - name: Validate Xcode project compatibility
        run: |
          # Attempt to open the project to confirm compatibility
          PROJECT_FILE=$(find . -name "explt.xcodeproj" | head -n 1)
          if [ -z "$PROJECT_FILE" ]; then
            echo "Error: explt.xcodeproj not found."
            exit 1
          fi
          # Check if the project format is compatible
          /Applications/Xcode_15.4.app/Contents/Developer/usr/bin/xcodebuild -list -project "$PROJECT_FILE" || exit 1

      # Step 4: Build the app
      - name: Build the app
        run: |
          PROJECT_FILE=$(find . -name "explt.xcodeproj" | head -n 1)
          ARCHIVE_PATH="${{ github.workspace }}/build/explt.xcarchive"

          xcodebuild -project "$PROJECT_FILE" \
                     -scheme explt \
                     -configuration Release \
                     -archivePath "$ARCHIVE_PATH" \
                     archive

          xcodebuild -exportArchive \
                     -archivePath "$ARCHIVE_PATH" \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath ${{ github.workspace }}/build

      # Step 5: Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: explt-ipa
          path: build/*.ipa
