name: Compile PoC Application (Use Xcode 13)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Detect available Xcode versions
      - name: List available Xcode versions
        id: list_xcode
        run: |
          echo "Available Xcode versions:"
          ls /Applications | grep Xcode
          echo "Targeting Xcode 13.x..."
          if [ ! -d "/Applications/Xcode_13.app" ] && [ ! -d "/Applications/Xcode_13.0.app" ]; then
            echo "Error: Xcode 13 is not installed on the runner."
            exit 1
          fi

      # Step 3: Switch to Xcode 13
      - name: Set up Xcode 13
        run: |
          if [ -d "/Applications/Xcode_13.app" ]; then
            sudo xcode-select --switch /Applications/Xcode_13.app/Contents/Developer
          elif [ -d "/Applications/Xcode_13.0.app" ]; then
            sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer
          else
            echo "Error: Unable to locate Xcode 13 directory."
            exit 1
          fi
          xcodebuild -version

      # Step 4: Build the app (Unsigned)
      - name: Build the app
        run: |
          PROJECT_FILE=$(find . -name "*.xcodeproj" | head -n 1)
          if [ -z "$PROJECT_FILE" ]; then
            echo "Error: No .xcodeproj file found."
            exit 1
          fi

          ARCHIVE_PATH="${{ github.workspace }}/build/explt.xcarchive"
          DERIVED_DATA_PATH="${{ github.workspace }}/build/DerivedData"

          # Clean the project
          xcodebuild -project "$PROJECT_FILE" \
                     -scheme explt \
                     -configuration Release \
                     -sdk iphoneos \
                     -derivedDataPath "$DERIVED_DATA_PATH" \
                     clean
          
          # Build the app (unsigned)
          xcodebuild -project "$PROJECT_FILE" \
                     -scheme explt \
                     -configuration Release \
                     -sdk iphoneos \
                     -derivedDataPath "$DERIVED_DATA_PATH" \
                     -archivePath "$ARCHIVE_PATH" \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_ENTITLEMENTS="" \
                     CODE_SIGNING_ALLOWED=NO \
                     archive
          
          # Export the app without signing
          xcodebuild -exportArchive \
                     -archivePath "$ARCHIVE_PATH" \
                     -exportPath ${{ github.workspace }}/build

      # Step 5: Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: explt-ipa
          path: build/*.ipa
